---
title: "Membership Disclosure"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(reticulate)

# Use your conda environment
use_condaenv("pysdg_dev", required = TRUE)
```

```{r}
# Import the Generator class.
synth.generate <- reticulate::import("pysdg.synth.generate") 
```

```{r,results='hide'}
# Read the population csv file
raw_data <- read_csv("tutorials/raw_data.csv")
```

```{r,results='hide'}
# Split the population into training and holdout datasets and save them to csv files. Use your desired split ratio.
set.seed(123)
train_indices <- sample(seq_len(nrow(raw_data)), size = 0.5 * nrow(raw_data))
raw_train <- raw_data[train_indices, ]
raw_holdout <- raw_data[-train_indices, ]

write.csv(raw_train, "tutorials/raw_train.csv", row.names = FALSE)
write.csv(raw_holdout, "tutorials/raw_holdout.csv", row.names = FALSE)
```

```{r,results='hide'}
# Use the training dataset to train your model.
gen1 <- synth.generate$Generator("synthcity_bayesian_network")
gen1$load('tutorials/raw_train.csv', 'tutorials/raw_info.json')
gen1$train()

# Extract the ENCODED version for the real dataset. Only the ENCODED versions should be used to calculate the membership risk, otherwise an error will be raised.
enc_real_train <- gen1$enc_real
```

```{r,results='hide'}
# Generate the required number of data points and synthetic version. In this example, we generate one synthetic dataset version with the same number of rows as the real dataset.
gen1$gen(num_rows = nrow(enc_real_train), num_synths = 1)

# Extract the ENCODED version for the synthetic dataset.
enc_synth <- gen1$enc_synths[[1]]
```

```{r,results='hide'}
# Create a 'dummy' generator to obtain the ENCODED version of the holdout dataset.
gen2 <- synth.generate$Generator()
gen2$load('tutorials/raw_holdout.csv', 'tutorials/raw_info.json')
enc_real_holdout <- gen2$enc_real
```

```{r,results='hide'}
# Remove the unnecessary columns from all ENCODED datasets. All columns that include '_missing' in their names should be removed. These columns are added by pysdg for tracking purposes and are not part of the original dataset.
enc_real_train <- enc_real_train %>% select(-contains('_missing'))
enc_synth <- enc_synth %>% select(-contains('_missing'))
enc_real_holdout <- enc_real_holdout %>% select(-contains('_missing'))
```

```{r,results='hide'}
# Use the ENCODED information about the datasets to extract the population size.
population_size <- gen1$enc_real_info$population_size[1]

# Define your desired size of the attack dataset. In this example, we use 20% of the training dataset.
attack_data_size <- as.integer(0.2 * nrow(enc_real_train))
```

```{r}
# Calculate the membership risk with default settings of quasi-identifiers (all variable names will be considered by default).
calc_mmbrshp_risk <- reticulate::import("pysdg.privacy.mmbrshp")$calc_mmbrshp_risk
res <- calc_mmbrshp_risk(enc_synth, enc_real_train, enc_real_holdout, population_size = population_size, attack_size = attack_data_size)
cat(sprintf("Relative F1 score = %f\n", res$f_rel))
cat(sprintf("Naive F1 score = %f\n", res$f_naive))
```

```{r}
# Calculate the membership risk when all variable names are explicitly passed as quasi-identifiers.
quasi_identifiers <- colnames(enc_real_train)

res <- calc_mmbrshp_risk(enc_synth, enc_real_train, enc_real_holdout, population_size = population_size, attack_size = attack_data_size, quasi_names = quasi_identifiers)
cat(sprintf("Relative F1 score = %f\n", res$f_rel))
cat(sprintf("Naive F1 score = %f\n", res$f_naive))
```


```{r}
# Calculate the membership risk when selected variables are used as quasi-identifiers. In this example, we use the ENCODED variable names corresponding to the indexes that were initially defined in the input json file.
quasi_identifiers <- gen1$enc_real_info$quasi_names

res <- calc_mmbrshp_risk(enc_synth, enc_real_train, enc_real_holdout, population_size = population_size, attack_size = attack_data_size, quasi_names = quasi_identifiers)
cat(sprintf("Relative F1 score = %f\n", res$f_rel))
cat(sprintf("Naive F1 score = %f\n", res$f_naive))
```



